name: 'Check-Runs'
description: 'Allow to report github check status'
inputs:
  check-name:
    description: 'The name of the check to run'
    required: true
  token:
    description: 'your GITHUB_TOKEN'
    required: true
  check-value:
    description: 'The specific status to report'
    required: false
  conclusion:
    description: 'The check conclusion'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
